[{"name": "test.test_matrix_power.MatrixPower.test_called", "status": "passed", "message": "", "passed": true, "points": ["p03-04.1"], "backtrace": []}, {"name": "test.test_matrix_power.MatrixPower.test_exponents", "status": "passed", "message": "", "passed": true, "points": ["p03-04.1"], "backtrace": []}, {"name": "test.test_matrix_power.MatrixPower.test_multiply", "status": "failed", "message": "\nArrays are not almost equal to 6 decimals\nMultiplying a matrix and its inverse should produce identity matrix! Input was matrix_power(a, 1) @ matrix_power(a, -1), where a=\n[[1 2]\n [3 4]]\nMismatched elements: 3 / 4 (75%)\nMax absolute difference: 3.\nMax relative difference: 1.\n x: array([[1., 0.],\n       [0., 1.]])\n y: array([[1., 2.],\n       [3., 4.]])", "passed": false, "points": ["p03-04.1"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part03-e04_matrix_power/test/test_matrix_power.py\", line 40, in test_multiply\n    \"Input was matrix_power(a, %i) @ matrix_power(a, -%i), where a=\\n%s\" %(i,i,a))\n", "  File \"/home2/anacondad3/lib/python3.7/site-packages/numpy/testing/_private/utils.py\", line 1047, in assert_array_almost_equal\n    precision=decimal)\n", "  File \"/home2/anacondad3/lib/python3.7/site-packages/numpy/testing/_private/utils.py\", line 846, in assert_array_compare\n    raise AssertionError(msg)\n"]}, {"name": "test.test_matrix_power.MatrixPower.test_one", "status": "passed", "message": "", "passed": true, "points": ["p03-04.1"], "backtrace": []}, {"name": "test.test_matrix_power.MatrixPower.test_zero", "status": "passed", "message": "", "passed": true, "points": ["p03-04.1"], "backtrace": []}]