[{"name": "test.test_vector_angles.VectorAngles.test_first", "status": "errored", "message": "shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)", "passed": false, "points": ["p02-15.1"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part02-e15_vector_angles/test/test_vector_angles.py\", line 24, in test_first\n    a = vector_angles(A, B)\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part02-e15_vector_angles/src/vector_angles.py\", line 12, in vector_angles\n    gg = np.dot(X, Y) / (normx * normy)\n", "  File \"<__array_function__ internals>\", line 6, in dot\n"]}, {"name": "test.test_vector_angles.VectorAngles.test_main", "status": "passed", "message": "", "passed": true, "points": ["p02-15.1"], "backtrace": []}, {"name": "test.test_vector_angles.VectorAngles.test_zero", "status": "errored", "message": "shapes (10,3) and (10,3) not aligned: 3 (dim 1) != 10 (dim 0)", "passed": false, "points": ["p02-15.1"], "backtrace": ["  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home2/anacondad3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part02-e15_vector_angles/test/test_vector_angles.py\", line 38, in test_zero\n    a = vector_angles(A, A)\n", "  File \"/home2/tmc/hy-data-analysis-with-python-spring-2020/part02-e15_vector_angles/src/vector_angles.py\", line 12, in vector_angles\n    gg = np.dot(X, Y) / (normx * normy)\n", "  File \"<__array_function__ internals>\", line 6, in dot\n"]}]